version: '3.9'

networks:
  botmobile-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # Servidor principal de Rasa
  rasa:
    image: hollyw00d337/botmobilev1.1:latest
    container_name: botmobile-rasa
    command: >
      rasa run
      --enable-api
      --port 5005
      --credentials /app/credentials_production.yml
      --endpoints /app/endpoints_production.yml
    volumes:
      - ./credentials_production.yml:/app/credentials_production.yml
      - ./endpoints_production.yml:/app/endpoints_production.yml
      - ./assets:/app/assets
    restart: unless-stopped
    depends_on:
      actions:
        condition: service_started
    networks:
      botmobile-network:
        ipv4_address: 172.20.0.20
    environment:
      - RASA_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - "5005:5005"

  # Servidor de acciones customizadas
  actions:
    image: hollyw00d337/botmobilev1.1:latest
    container_name: botmobile-actions
    command: rasa run actions --port 5055
    restart: unless-stopped
    networks:
      botmobile-network:
        ipv4_address: 172.20.0.30
    environment:
      - RASA_SDK_ENDPOINT_URL=http://actions:5055/webhook
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
